# -*- coding: utf-8 -*-
"""Copia de Copia de Tarea-Regresion-Lineal-Grupo#2.R

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1egBOWCiZJymHKJl9vA-vVXzsJvh-Bq6n

#Tarea #2 - Regresión Lineal Simple
 # Integrantes
 - Kevin Campuzano
 - Luis Ugarte
 - Isaias Bajaña
 - Manuel Naranjo


Instrucciones

6. Evalúen diagnóstico gráfico.
7. Evalúen heterocedasticidad.
8. Apliquen errores robustos si corresponde.
9. Evalúen autocorrelación si el contexto lo justifica.
10. Presenten una conclusión breve.

Cargamos las librerias
"""

# Instalar solo si no los tienes
install.packages("ISLR2")
install.packages("lmtest")
install.packages("sandwich")
install.packages("car")

"""Primero cargaremos la data que vamos a analizar

### 1. Seleccionen el dataset Auto o Credit.
"""

library(ISLR2)
library(lmtest)
library(sandwich)
library(dplyr)

data(Auto)

"""### 2. Definan una variable respuesta continua."""

R_auto <- Auto %>%
  select(where(is.numeric)) %>%
  cor(use = "complete.obs")
round(R_auto, 2)

"""Se escoge `mpg` como variable respuesta porque presenta correlaciones fuertes con la mayoria de las variables del dataset, especialmente negativas con `weight`, `displacement`` y `horsepower`, lo que indica que exiten relaciones lineales claras y aprovechables para un modelo de regresión.

Eliminaremos variables rebundantes que estan muy correlacionadas como son `cylinders` y `displacement` cor es **0.95**, otra correlacion muy alta es `displacement` y `weight` cor es **0.93**.

`acceleration` es el predictor más débil, su correlación con `mpg` es **0.42**, ademas de que hay correlación negativa con `horsepower` siendo **-0.69**, es lógico que autos con más potencia aceleran más rápido.

`year` y `origin` tienen una correlacion positiva con `mpg`, lógicamente autos más nuevos consumen menos por lo tanto la eficiencia mejor con el tiempo. Con `origin` lo que podemos deducir es que autos de ciertos origenes tienden a ser más eficientes.

### 3. Ajusten un modelo de regresión lineal simple.

Observando la matriz de correlación podemos observar algunas relaciones sólidas para modelos de regresión simple. A continuación detallaremos la rls entre mpg y horsepower:
"""

# mpg ~ horsepower, con una correlacion de -0.78
mpg_llm <- lm(mpg ~ horsepower, data = Auto)
summary(mpg_llm)

"""## Discusión
**Pendiete de -0.1578**, por cada 1 caballo de fuerza adicional, se espera que el redimiento del auto disminuye en 0.158 mpg.
<br>Un auto de 100 hp -> 39.94(Intercepto) - 0.158 * 100 = 24.1 mpg</br>
El modelo de regresión simple `mpg ~ horsepower` es estadísticamente significativo y explica el 60.6% de la variabilidad del consumo. La relación es negativa: mayor potencia implica menor eficiencia. Sin embargo, un R2 de 0.60 sugiere que agregar más predictores mejoraría el modelo, lo que motiva el paso a regresión multiple.

Detallamos la **RLS entre mpg y el peso:**
"""

# mpg ~ weight con una correlacion -0.83
mpg_weight_llm <- lm(mpg ~ weight, data = Auto)
summary(mpg_weight_llm)

"""## Discusión
Entre los 2 modelos simples evaluados, `mpg ~ weight` es superior: explica el 69.3% de la variabilidad (vs 60.6%) y tiene menor error residual (4.33 vs 4.91 mpg). Esto es consistente con la matriz de correlación, donde `weight` mostró la correlación más fuerte con `mpg`. Aún así, ambos modelos dejan más del 30% de variabilidad sin explicar, lo que motiva construir un modelo de regresión múltiple incorporando ambas variables.
"""

# mpg ~ year correlación 0.58 (positiva)
mpg_year_llm <- lm(mpg ~ year, data = Auto)
summary(mpg_year_llm)

"""## Discusión
El modelo `mpg ~ year` es el más débil de los tres evaluados individualmente, pero es el único con relación positiva: los autos más recientes son más eficientes. Aunque su poder explicativo solo es moderado, `year` captura un efecto temporal distinto al de las variables físicas del auto, por lo que su inclusión en el modelo múltiple puede aportar información complementaria.
"""

# Para verlos todos de una vez en una sola figura
par(mfrow = c(1, 3))

# Gráfico 1: mpg ~ horsepower
plot(Auto$horsepower, Auto$mpg,
     pch = 19, col = "steelblue",
     xlab = "Horsepower", ylab = "MPG",
     main = "mpg ~ horsepower")
abline(mpg_llm, col = "red", lwd = 2)

# Gráfico 2: mpg ~ weight
plot(Auto$weight, Auto$mpg,
     pch = 19, col = "steelblue",
     xlab = "Weight", ylab = "MPG",
     main = "mpg ~ weight")
abline(mpg_weight_llm, col = "red", lwd = 2)

# Gráfico 3: mpg ~ year
plot(Auto$year, Auto$mpg,
     pch = 19, col = "steelblue",
     xlab = "Year", ylab = "MPG",
     main = "mpg ~ year")
abline(mpg_year_llm, col = "red", lwd = 2)

# Regresar a una sola figura
par(mfrow = c(1, 1))

"""##4. Ajusten un modelo de regresión lineal múltiple."""

modelo_multiple = lm(mpg ~ weight + horsepower + year, data = Auto)
summary(modelo_multiple)

"""horsepower se eliminó porque en el modelo múltiple resulta estadísticamente no significativo (p > 0.05), lo que indica que su efecto ya está capturado por weight (multicolinealidad)"""

modelo_multiple = lm(mpg ~ weight  + year, data = Auto)
summary(modelo_multiple)

"""## Discusión
El modelo múltiple `mpg ~ weight + year` mejora sustancialmente el ajuste respecto a cualquier modelo simple, explicando el 80.8% de la variabilidad de `mpg`(RSE = 3.43). Sin embargo, `horsepower` resulta no significativo en presencia de `weight`, lo que sugiere multicolinealidad entre ambas variables. Los predictores más importantes son `weight` y `year`, reflejando que autos más ligeros y más recientes son más eficientes en combustible.

# 5. Interpreten los coeficientes principales

B_1 (weight) -> Por cada unidad de peso extra, se espera que la eficiencia del galón de gasolina disminuya en 0.006632 mpg.
B_2 (year) -> Por cada año más reciente que sea el carro, se espera que la eficiencia del galón de gasolina aumente en 0.7573 mpg.
"""

coef(summary(modelo_multiple))
confint(modelo_multiple)

"""# 6. Evalúen diagnóstico gráfico."""

par(mfrow = c(2, 2))
plot(modelo_multiple)
par(mfrow = c(1, 1))

cooks.distance(modelo_multiple) |>
  sort(decreasing = TRUE) |>
  head()

"""El gráfico número 1 nos está indicando que no hay linealidad, como nos damos cuenta la curva tiende a formar una u, lo que descarta la linealidad, adicional, los residuos no esán distribuidos alrededor del 0, por lo que nos demuestra probable heterocedasticidad.
El gráfico número 2 nos indica que los residuos no son perfectamente normales, pues ay una desviación en la cola derecha, adicional hay posibles outliers.
En el gráfico 3 se nos vuelve a mostrar problemas de homocedasticidad, pues la varianza del error no se ve constante.

# 7. Evalúen heterocedasticidad.
"""

bptest(modelo_multiple)

"""Con un nivel de confianza del 95% se rechaza la posibilidad de homocedasticidad, puesto que H_0=varianza constante vs H_A: Varianza no constante. Por ende, existe heterocedasticidad.

"""



"""## 8. Apliquen errores robustos si corresponde."""

coeftest(modelo_multiple,
         vcov = vcovHC(modelo_multiple, type = "HC1"))

"""## 9. Evalúen autocorrelación si el contexto lo justifica."""

dwtest(modelo_multiple)

"""DW = 1.2304, p-value = 5.626e-15,lo que indica evidencia estadística de autocorrelación positiva en los residuos.

**Sin embargo**, el dataset Auto **no es una serie de tiempo** propiamente dicha. La autocorrelación detectada se explica por la estructura interna del dataset: las observaciones están ordenadas por year, por lo que autos del mismo año aparecen consecutivos y comparten características similares.

**Por esta razón, no se aplican correcciones de series de tiempo**

# 10. Presenten una conclusión breve.

El modelo `mpg ~ weight + year` explica el 80.7% de la variabilidad del consumo (R² ajustado = 0.806), siendo **weight** y **year** los predictores significativos. Se confirmó heterocedasticidad mediante el test de Breusch-Pagan, por lo que se aplicaron errores robustos HC1 sin alterar las conclusiones. La autocorrelación detectada (DW = 1.23) se atribuye al ordenamiento interno del dataset y no a una dependencia temporal real. El modelo es útil y parsimonioso para explicar la eficiencia en combustible.

# Preguntas

*   **¿Qué variables son estadísticamente significativas?**
Los predictores más importantes son weight y year, reflejando que autos más ligeros y más recientes son más eficientes en combustible.
Horsepower fue descartada del modelo múltiple por no ser significativa en presencia de weight, evidenciando multicolinealidad entre ambas variables.

*   **¿Cómo interpretan el coeficiente más importante?**
**weight** es el predictor más relevante: por cada libra adicional de peso, se espera que la eficiencia disminuya en 0.0066 mpg, manteniendo el año del modelo constante. Esto tiene sentido físico: autos más pesados requieren más combustible para moverse.

*   **¿Hay evidencia de heterocedasticidad?**
Si,el test de Breusch-Pagan arrojó p < 0.05, por lo que se rechaza la hipótesis de varianza constante.

*   **¿Cambian las conclusiones usando errores robustos?**
Al aplicar errores robustos (HC1),los errores estándar se ajustan ante la heterocedasticidad, pero weight y year se mantienen significativos. Las conclusiones sobre la dirección e importancia de los predictores no cambian.

*   **¿El modelo es útil para explicar la variable respuesta?**
Sí. El modelo `mpg ~ weight + year` explica el 80.7% de la variabilidad del consumo (R² ajustado ≈ 0.806) lo que lo convierte en un modelo que explica correctamente el comportamiento de la variable
"""